hanlight/hanlight-frontend-web

src/components/main/main.component.tsx, src/components/main/timeTable/main-timeTable.component.tsx, src/components/timeTable/index.ts, src/components/timeTable/timeTable.component.tsx, src/container/timeTable/index.ts, src/container/timeTable/timeTable.container.tsx, src/lib/styles/Empty.ts, src/lib/styles/index.ts, src/lib/svg/left-illust.svg, src/lib/svg/right-illust.svg, src/pages/timeTable/index.ts, src/pages/timeTable/timeTable.page.tsx, src/store/reducer/timeTable.reducer.ts
timeTable component, container, page.
Background images of timetable page.
Storing timetable response data from index 1 of the timetable array.
Today var is no longer reduce 1.
=> Timetable feature

src/components/board/comment/boardComment.component.tsx, src/components/board/comment/commentForm/boardCommentForm.component.tsx, src/components/board/feed/boardFeed.component.tsx, src/components/board/feed/feedItem/boardFeedItem.component.tsx, src/components/board/form/boardForm.component.tsx, src/components/notice/detail-notice/detail-noticePost/detail-noticePost.component.tsx, src/container/board/comment/boardComment.container.tsx, src/container/board/comment/commentForm/boardCommentForm.container.tsx, src/container/board/comment/commentForm/index.ts, src/container/board/feed/boardFeed.container.tsx, src/container/notice/detail-notice/detail-noticePost/detail-noticePost.container.tsx, src/lib/hooks/useInput.tsx, src/pages/board/role/boardRole.page.tsx, src/pages/notice/detail-notice/detaill-notice.page.tsx, src/store/action/board.action.ts, src/store/action/notice.action.ts, src/store/model/board.model.ts, src/store/reducer/board.reducer.ts, src/store/saga/board.saga.ts, src/store/saga/notice.saga.ts
=> boardCommentForm Feature

src/components/board/board.component.tsx, src/components/board/comment/boardComment.component.tsx, src/components/board/comment/commentItem/boardCommentItem.component.tsx, src/components/board/feed/boardFeed.component.tsx, src/components/board/feed/feedItem/boardFeedItem.component.tsx, src/components/board/form/boardForm.component.tsx, src/components/calendar/main-calendar/main-calendar.component.tsx, src/components/meal/main-meal/main-meal.component.tsx, src/components/notice/main-notice/main-notice.component.tsx, src/components/timeTable/main-timeTable/main-timeTable.component.tsx, src/container/board/comment/boardComment.container.tsx, src/container/board/feed/boardFeed.container.tsx, src/root.tsx, src/store/action/board.action.ts, src/store/model/board.model.ts, src/store/reducer/board.reducer.ts, src/store/saga/board.saga.ts
=> Like Feature & Fixed Small bugs

src/components/board/board.component.tsx, src/components/board/comment/boardComment.component.tsx, src/components/board/comment/commentItem/boardCommentItem.component.tsx, src/components/board/feed/boardFeed.component.tsx, src/components/board/feed/feedItem/boardFeedItem.component.tsx, src/components/board/report/boardReport.component.tsx, src/components/board/report/index.ts, src/components/main/main.component.tsx, src/container/board/comment/boardComment.container.tsx, src/container/board/feed/boardFeed.container.tsx, src/container/board/index.ts, src/container/board/report/boardReport.container.tsx, src/container/board/report/index.ts, src/index.scss, src/lib/hooks/useInput.tsx, src/store/action/board.action.ts, src/store/model/board.model.ts, src/store/reducer/board.reducer.ts, src/store/saga/board.saga.ts
Board Report component, container, feature
Like Api GET -> POST
=> Board Report Feature

public/index.html, public/manifest.json, src/components/board/board.component.tsx, src/components/board/comment/boardComment.component.tsx, src/components/board/comment/commentItem/boardCommentItem.component.tsx, src/components/board/feed/boardFeed.component.tsx, src/components/board/feed/feedItem/boardFeedItem.component.tsx, src/components/board/form/boardForm.component.tsx, src/components/board/report/boardReport.component.tsx, src/components/header/header.component.tsx, src/components/main/main.component.tsx, src/container/board/comment/boardComment.container.tsx, src/container/board/feed/boardFeed.container.tsx, src/store/action/board.action.ts, src/store/action/error.action.ts, src/store/model/board.model.ts, src/store/reducer/board.reducer.ts, src/store/reducer/error.reducer.ts, src/store/saga/board.saga.ts, src/store/saga/calendar.saga.ts, src/store/saga/error.saga.ts, src/store/saga/meal.saga.ts, src/store/saga/notice.saga.ts, src/store/saga/timeTable.saga.ts, src/store/saga/user.saga.ts
* change props logic to inherit *board*Status props
* change state by *board*Status props
=> fixed: board refactoring & catch some bugs

src/components/calendar/calendarItem/calendarItem.component.tsx, src/components/calendar/detail-calendar/detail-calendar.component.tsx, src/components/meal/main-meal/main-meal.component.tsx, src/components/meal/mealItem/mealItem.component.tsx, src/components/modal/modal.components.tsx, src/components/notice/main-notice/main-notice.component.tsx, src/components/notice/main-notice/noticeItem/main-noticeItem.component.tsx, src/components/timeTable/main-timeTable/timeTableItem/main-timeTableItem.component.tsx, src/lib/styles/Device.ts, src/lib/styles/index.ts, src/pages/main/main.page.tsx, src/pages/timer/timer.page.tsx
##Add
Device.ts to make comfortable responsive UI
##Fixed
main page respond to 1024px
detail calendar page respond to 1024px
=> Main Page & Detail Calendar Page Respond to 1024px

src/components/error/error.component.tsx, src/components/header/header.component.tsx, src/components/header/menu/headerMenu.component.tsx, src/components/main/main.component.tsx, src/components/meal/detail-meal/detail-meal.component.tsx, src/components/meal/detail-meal/item/detail-mealItem.component.tsx, src/components/notice/detail-notice/detail-noticeList/detail-noticeList.component.tsx, src/components/notice/detail-notice/detail-noticePost/detail-noticePost.component.tsx, src/components/profile/profile.component.tsx, src/components/timeTable/detail-timeTable/detail-timeTable.component.tsx, src/components/timer/timer.component.tsx, src/components/user/phoneCheck/phoneCheck.component.tsx, src/lib/styles/labels.ts, src/lib/svg/notice-icon.svg, src/pages/timeTable/detail-timeTable/detail-timeTable.page.tsx
* fixed: meal month load last month
* fixed: headerMenu items covered by illust
* fixed: profile & timer UX
* feat: all features media query without Board
=> Media query & fix some bugs

src/components/auto/autoErrorCheck/autoErrorCheck.component.tsx, src/components/board/form/boardForm.component.tsx, src/container/auto/autoErrorCheck/autoErrorCheck.container.tsx, src/lib/baseUrl/index.ts
baseURL test to api
boardForm submit button active color
=> BoardForm Submit Button Color & baseURL

src/components/auto/autoErrorCheck/autoErrorCheck.component.tsx, src/components/calendar/detail-calendar/item/detail-calendarItem.component.tsx, src/components/calendar/main-calendar/item/main-calendarItem.component.tsx, src/components/error/error.component.tsx, src/components/main/main.component.tsx, src/index.scss, src/lib/baseUrl/index.ts, src/lib/font/font.scss, src/pages/footer/footer.page.tsx
503 error treatment
footer instagram link
=> Error Page & Footer Fix

src/components/hanseithon/current/currentItem/ht-currentItem.component.tsx, src/components/hanseithon/modal/ht-modal.component.tsx, src/components/hanseithon/modal/match/match-modal.component.tsx, src/container/hanseithon/main/acceptPage/acceptPage.container.tsx
=> Fix hanseithon

public/index.html
=> feat: analytics

src/components/meal/detail-meal/detail-meal.component.tsx
Detail meal first item not found
=> fixed: detail meal first item not working

src/components/hanseithon/hanseithon.component.tsx, src/components/hanseithon/main/ht-main.component.tsx, src/components/hanseithon/participation/ht-participation.component.tsx, src/components/hanseithon/participation/index.ts, src/components/hanseithon/participation/teamItem/ht-teamItem.component.tsx, src/components/hanseithon/participation/teamItem/index.ts, src/container/hanseithon/main/ht-main.container.tsx, src/container/hanseithon/participation/ht-participation.container.tsx, src/container/hanseithon/participation/index.ts, src/pages/hanseithon/participation/ht-participation.page.tsx, src/pages/hanseithon/participation/index.ts, src/store/action/hanseithon.action.ts, src/store/model/hanseithon.model.ts, src/store/reducer/hanseithon.reducer.ts, src/store/saga/hanseithon.saga.ts
participation page
get theme, get judgement button
get theme, get judgement redux
=> Feature hanseithon

src/components/hanseithon/main/ht-main.component.tsx, src/store/reducer/hanseithon.reducer.ts, src/store/saga/hanseithon.saga.ts
=> Hanseithon judgment

src/components/board/comment/boardComment.component.tsx, src/components/board/comment/commentItem/boardCommentItem.component.tsx, src/components/board/form/boardForm.component.tsx
allow Graduate type to write feed and comment
=> Board Permission

src/components/hanseithon/main/ht-main.component.tsx, src/components/hanseithon/main/participantItem/ht-participantItem.component.tsx, src/components/hanseithon/main/sponsor/ht-sponsor.component.tsx
##Change
fix mobile Title font size
fix participant list grid gap (tablet: 3line, mobile: 2line)
fix sponsor component font-family typo
=> Fix Hanseithon Final main page

src/components/board/feed/feedItem/boardFeedItem.component.tsx, src/components/board/photoDetail/photoDetail.component.tsx, src/components/profile/profile.component.tsx, src/lib/svg/hm-list-icon.svg, src/store/reducer/user.reducer.ts, src/store/saga/board.saga.ts, yarn.lock
mobile image detail dimmed area touch error
=> Fix mobile image detail view touch error

src/components/board/likeList/likeListItem/likeListItem.component.tsx
like list profile image exception handling
=> Fix like list

src/components/calendar/detail-calendar/detail-calendar.component.tsx, src/components/calendar/detail-calendar/item/detail-calendarItem.component.tsx
calendar item's date & today logic
=> Fix calendar item date

src/components/meal/detail-meal/detail-meal.component.tsx
Detail meal page's today test logic also compares months.
=> Fix Detail Meal Page logic

package.json, yarn.lock
Move all @types package into devDependencies
=> Move all @types package into devDependencies

src/components/board/option/comment/comment-option.component.tsx, src/components/board/option/feed/edit/feed-edit.component.tsx, src/components/board/option/feed/feed-option.component.tsx, src/components/board/report/boardReport.component.tsx, src/lib/types.ts, src/store/action/user.action.ts, src/store/model/common/common.model.ts, src/store/model/common/index.ts, src/store/model/index.ts, src/store/model/user.model.ts, src/store/reducer/user.reducer.ts, src/store/saga/user.saga.ts
- 타입 임포트해서 쓸 수 있게 변경
- 타입 묶음 작업
=> Make User base type
